### ISSUE TITLE
Dividends?

### ISSUE THREAD

**Issue by buddhawilliams** [scheb/stock-panel#291]
Hi,
I really like where you are going with this. I have forked it to have a play. Are you planning on adding Dividend recording to it? My experience with a lot of these portfolio managers is that they completely ignore dividends, though for so many investors it is where they get the most return.
I've never used Symfony, or yarn or node (I use Slim, or legacy code 😝 and very little JS) and looking at your code, I have managed to get heartily confused. I will have a bash at adding dividends, but I am sure I will break a lot of your code - there are more layers in there than I am comfortable with. 
I'm hoping it's on your agenda, so I could perhaps help with something a little less daunting to start with 😁

**Comment by scheb** [comment]
The application is working fine for me as it is, so I'm not planning to extend the application any further. It's a project that I've created for myself some years ago and shared on GitHub, in case someone else finds it useful. And to benefit from GitHub automation, such as Dependabot, to keep the dependencies automatically up-to-date. I'm not having aspirations to maintain the project for anyone but myself, sorry.

If Symfony/Yarn is not your thing, have a look at https://github.com/scheb/yahoo-finance-api, which is a library that I actively maintain for other people to use. It already has API methods for fetching dividends data. So you could use that and build your own little app around it.

**Comment by buddhawilliams** [comment]
Thanks for the response. I'll check out the library instead.
Cheers
